
# server.port = 7901
# server.servlet.context-path = /
server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://rm-wz936477ppnwe9zamfo.mysql.rds.aliyuncs.com:3306/shiro-web?characterEncoding=utf-8
    username: syp_test
    password: a123456!
  
  
mybatis:
  mapper-locations: classpath:com/yucong/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
  
  
  
    